name: Open Podcast and Log Screenshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  open-podcast:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Open Apple Podcast
      run: |
        osascript -e 'tell application "Podcasts" to open location "https://podcasts.apple.com/de/podcast/die-sogenannte-gegenwart/id1522895163?i=1000695431521"'
        sleep 10 # Wait for the podcast to open
    
    - name: Take screenshot
      run: |
        screencapture podcast_screenshot.png

    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: podcast_screenshot
        path: podcast_screenshot.png
