name: Open Podcast and Log Screenshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  open-podcast:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Launch Podcasts
        run: |
          osascript -e '
            tell application "Podcasts" to activate
            delay 10
          '

      - name: Screenshot After Launch
        run: screencapture step1_launch.png

      - name: Attempt to Press Enter Instead of Continue
        run: |
          osascript -e '
            tell application "System Events"
              tell process "Podcasts"
                try
                  keystroke return
                end try
              end tell
            end tell
            delay 10
          '

      - name: Screenshot After Pop-up
        run: screencapture step2_popup.png

      - name: Open Desired Podcast Episode
        run: |
          osascript -e '
            tell application "Podcasts"
              open location "https://podcasts.apple.com/de/podcast/die-sogenannte-gegenwart/id1522895163?i=1000695431521"
              delay 10
            end tell
          '

      - name: Screenshot After Opening Episode
        run: screencapture step3_opened_episode.png

      # UPDATED STEP: Click at Coordinates (1155, 475)
      - name: Click at Coordinates (1155, 475)
        run: |
          osascript -e '
            tell application "System Events"
              tell process "Podcasts"
                set frontmost to true
                try
                  click at {1418, 384}
                  key code 125
                  key code 125
                  key code 125
                  key code 125
                  key code 125
                  key code 125
                  key code 125
                end try
              end tell
            end tell
            delay 10
          '

      - name: Screenshot After Clicking at Coordinates
        run: screencapture step4_transcript_clicked.png

      - name: Open Transcript
        run: |
          osascript -e '
            tell application "System Events"
              tell process "Podcasts"
                set frontmost to true
                try
                  keystroke return
                end try
              end tell
            end tell
            delay 10
          '

      - name: Screenshot After Clicking at Coordinates
        run: screencapture step5_transcript_clicked.png

      - name: Zip the Podcasts Cache Folder
        run: |
          zip -r podcasts_cache.zip "$HOME/Library/Group Containers/243LU875E5.groups.com.apple.podcasts/Library/Cache"

      - name: Upload All Screenshots and Cache Folder
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-and-cache
          path: |
            step1_launch.png
            step2_popup.png
            step3_opened_episode.png
            step4_transcript_clicked.png
            podcasts_cache.zip
